export const theme = {
  primary: {
    backgroundColor: "hsl(27, 66%, 92%)",
    topBarTextColor: "#fff",
    topBarBackgroundColor: "hsl(10, 79%, 65%)",
    topBarCircleOutline: "#fff",
    topBarCircle: "black",
    mianBoxTextColor: "black",
    mianBoxBackgroundColor: "#fff",
    columnColor: "hsl(10, 79%, 65%)",
    highestValueColumnColor: "hsl(186, 34%, 60%)",
    onHoverColumnBox: "black",
    onHoverColumnBoxTest: "#fff",
    main: {
      main: "blue",
    },
  },
  madness: {
    backgroundColor: "hsl(27, 66%, 92%)",
    topBarTextColor: "#fff",
    topBarBackgroundColor: "hsl(10, 79%, 65%)",
    topBarCircleOutline: "#fff",
    topBarCircle: "black",
    mianBoxTextColor: "black",
    mianBoxBackgroundColor: "#fff",
    columnColor: "hsl(10, 79%, 65%)",
    highestValueColumnColor: "hsl(186, 34%, 60%)",
    onHoverColumnBox: "black",
    onHoverColumnBoxTest: "#fff",
  },
  neatColor: {
    backgroundColor: "#ffbe0b",
    topBarTextColor: "#fff",
    topBarBackgroundColor: "#3a86ff",
    topBarCircleOutline: "#fff",
    topBarCircle: "black",
    mianBoxTextColor: "#ffc6ff",
    mianBoxBackgroundColor: "#fb5607",
    columnColor: "#3a86ff",
    highestValueColumnColor: "#8338ec",
    onHoverColumnBox: "black",
    onHoverColumnBoxTest: "#fff",
    main: "hsl(10, 79%, 65%)",
  },
  pastel: {
    backgroundColor: "#9c89b8",
    topBarTextColor: "#fff",
    topBarBackgroundColor: "#bdb2ff",
    topBarCircleOutline: "#fff",
    topBarCircle: "black",
    mianBoxTextColor: "#ffc6ff",
    mianBoxBackgroundColor: "#f0a6ca",
    columnColor: "#f0e6ef",
    highestValueColumnColor: "#efc3e6",
    onHoverColumnBox: "black",
    onHoverColumnBoxTest: "#fff",
    main: "hsl(10, 79%, 65%)",
  },
};
