export const theme = {
  primary: {
    backgroundColor: "hsl(27, 66%, 92%)",
    topBarTextColor: "#fff",
    topBarBackgroundColor: "hsl(10, 79%, 65%)",
    topBarCircleOutline: "#fff",
    topBarCircle: "black",
    mianBoxTextColor: "black",
    mianBoxBackgroundColor: "#fff",
    columnColor: "hsl(10, 79%, 65%)",
    highestValueColumnColor: "hsl(186, 34%, 60%)",
    onHoverColumnBox: "black",
    onHoverColumnBoxTest: "#fff",
    main: {
      main: "blue",
    },
  },
  madness: {
    mianBoxTextColor: "red",
  },
  neatColor: {
    backgroundColor: "hsl(27, 66%, 92%)",
    topBarTextColor: "#fff",
    topBarBackgroundColor: "hsl(10, 79%, 65%)",
    topBarCircleOutline: "#fff",
    topBarCircle: "black",
    mianBoxTextColor: "#ffc6ff",
    mianBoxBackgroundColor: "#fff",
    columnColor: "hsl(10, 79%, 65%)",
    highestValueColumnColor: "hsl(186, 34%, 60%)",
    onHoverColumnBox: "black",
    onHoverColumnBoxTest: "#fff",
    main: "hsl(10, 79%, 65%)",
  },
};
